function setCookie(c_name,value,exdays)
{var exdate=new Date();exdate.setDate(exdate.getDate()+ exdays);var c_value=escape(value)+((exdays==null)?"":"; expires="+exdate.toUTCString());document.cookie=c_name+"="+ c_value;}
function resizeVideo(){if(jQuery('.embedded_videos').length){var iframe_width=jQuery('.embedded_videos').parent().width();var_iframe_height=iframe_width/1.37;jQuery('.embedded_videos iframe ').each(function(){jQuery(this).attr('width',iframe_width);jQuery(this).attr('height',var_iframe_height);});jQuery('.embedded_videos div.video-js ').each(function(){jQuery(this).attr('width',iframe_width);jQuery(this).attr('height',var_iframe_height);jQuery(this).css('width',iframe_width);jQuery(this).css('height',var_iframe_height);});}}
jQuery(document).ready(function(){setTimeout('viewPort()',3000);resizeVideo();jQuery(window).resize(function(){viewPort();resizeVideo();});jQuery(function(){var msie6=jQuery.browser=='msie'&&jQuery.browser.version<7;if(!msie6&&jQuery('.sticky-bar').length!=0){var top=jQuery('#sticky-bar').offset().top- parseFloat(jQuery('#sticky-bar').css('margin-top').replace(/auto/,0));jQuery(window).scroll(function(event){var y=jQuery(this).scrollTop();if(y>=top-0){jQuery('#sticky-bar').addClass('fixed');}else{jQuery('#sticky-bar').removeClass('fixed');}});}});jQuery('.cosmo-acc-container').hide();jQuery('.cosmo-acc-trigger:first').addClass('active').next().show();jQuery('.cosmo-acc-trigger').click(function(){if(jQuery(this).next().is(':hidden')){jQuery('.cosmo-acc-trigger').removeClass('active').next().slideUp();jQuery(this).toggleClass('active').next().slideDown();}
return false;});jQuery("ul.sf-menu").supersubs({minWidth:12,maxWidth:32,extraWidth:1}).superfish({delay:200,speed:250});jQuery(function(){var msie6=jQuery.browser=='msie'&&jQuery.browser.version<7;if(!msie6&&jQuery('.sticky-bar').length!=0){var top=jQuery('#sticky-bar').offset().top- parseFloat(jQuery('#sticky-bar').css('margin-top').replace(/auto/,0));jQuery(window).scroll(function(event){var y=jQuery(this).scrollTop();if(y>=top-0){jQuery('#sticky-bar').addClass('fixed');}else{jQuery('#sticky-bar').removeClass('fixed');}});}});jQuery(function(){jQuery('a.close').click(function(){jQuery(jQuery(this).attr('href')).slideUp();jQuery.cookie(cookies_prefix+"_tooltip",'closed',{expires:365,path:'/'});jQuery('.header-delimiter').removeClass('hidden');return false;});});jQuery('.readmore').mosaic();jQuery('.circle, .gallery-icon').mosaic({opacity:0.5});jQuery('.fade').mosaic({animation:'slide'});jQuery('.cosmo-tabs').each(function(){jQuery(this).find('.tabs-container').not(':first').css('display','none');jQuery(this).find('ul li:first').addClass('tabs-selected');jQuery(this).find('ul li a').click(function(){if(jQuery(this).parent().hasClass('tabs-selected')){return false;}
var tabId=jQuery(this).attr('href');jQuery(this).parent().parent().find('.tabs-selected').removeClass('tabs-selected');jQuery(this).parent().addClass('tabs-selected');jQuery(this).parents('.cosmo-tabs').find('.tabs-container').not(tabId).css('display','none');jQuery(this).parents('.cosmo-tabs').find(tabId).css('display','block');return false;})});jQuery('.toggle-menu').click(function(){jQuery('.mobile-nav-menu').slideToggle();});jQuery(document).ready(function(){jQuery(".mobile-nav-menu").saccordion({saccordion:false,speed:200,closedSign:'',openedSign:''});});jQuery(document).ready(function(){jQuery('aside.widget').append('<div class="clear"></div>');});var sidebar_type=jQuery('#secondary').attr('class');jQuery(window).on('resize load orientationChanged',function(){if(jQuery(this).width()<767){jQuery('#d-menu').addClass('hide');jQuery('.mobile-menu').removeClass('hide');jQuery('.mobile-menu').css('display','block');jQuery('#sticky-bar').css('display','none');jQuery('.keyboard-demo').css('display','none');jQuery('#menu-login').css('display','none');jQuery('#secondary').removeClass('right-sidebar left-sidebar');}else{jQuery('#d-menu').removeClass('hide');jQuery('.mobile-menu').css('display','none');jQuery('.mobile-menu').addClass('hide');jQuery('#sticky-bar').css('display','block');jQuery('.keyboard-demo').css('display','block');jQuery('#menu-login').css('display','block');jQuery('#secondary').addClass(sidebar_type);}});if(jQuery().slides){jQuery(".dynamic .cosmo_twitter").slides({play:5000,effect:'fade',generatePagination:false,autoHeight:true});}
jQuery('.show_colors').click(function(){jQuery('.hide_colors').show();jQuery('.show_colors').hide();jQuery(".style_switcher").animate({left:"10px"},500);});jQuery('.hide_colors').click(function(){jQuery('.hide_colors').hide();jQuery('.show_colors').show();jQuery(".style_switcher").animate({left:"-152px"},500);});jQuery('ul.widget_tabber li a').click(function(){jQuery(this).parent('li').parent('ul').find('li').removeClass('active');jQuery(this).parent('li').parent('ul').parent('div').find('div.tab_menu_content.tabs-container').fadeTo(200,0);jQuery(this).parent('li').parent('ul').parent('div').find('div.tab_menu_content.tabs-container').hide();jQuery(jQuery(this).attr('href')+'_panel').fadeTo(600,1);jQuery(this).parent('li').addClass('active');});jQuery('.open_title').click(function(){if(jQuery(this).find('a').hasClass('show')){jQuery(this).find('a').removeClass('show');jQuery(this).find('a').addClass('toggle_close');jQuery(this).find('.title_closed').hide();jQuery(this).find('.title_open').show();}else{jQuery(this).find('a').removeClass('toggle_close');jQuery(this).find('a').addClass('show');jQuery(this).find('.title_open').hide();jQuery(this).find('.title_closed').show();}
jQuery('.cosmo-toggle-container').slideToggle("slow");});jQuery('.close_title').click(function(){if(jQuery(this).find('a').hasClass('hide')){jQuery(this).find('a').removeClass('toggle_close');jQuery(this).find('a').addClass('show');jQuery(this).find('.title_open').hide();jQuery(this).find('.title_closed').show();}else{jQuery(this).find('a').removeClass('show');jQuery(this).find('a').addClass('toggle_close');jQuery(this).find('.title_closed').hide();jQuery(this).find('.title_open').show();}
jQuery('.cosmo-toggle-container').slideToggle("slow");});jQuery('.cosmo-acc-container').hide();jQuery('.cosmo-acc-trigger:first').addClass('active').next().show();jQuery('.cosmo-acc-trigger').click(function(){if(jQuery(this).next().is(':hidden')){jQuery('.cosmo-acc-trigger').removeClass('active').next().slideUp();jQuery(this).toggleClass('active').next().slideDown();}
return false;});jQuery(window).scroll(function(){if(jQuery(this).scrollTop()!=0){jQuery('#toTop').fadeIn();}else{jQuery('#toTop').fadeOut();}});jQuery('#toTop').click(function(){jQuery('body,html').animate({scrollTop:0},300);});jQuery('div.sticky-bar li.my-add').mouseover(function(){jQuery('.show-first').hide();jQuery('.show-hover').fadeIn(10);});jQuery('#sticky-bar').mouseleave(function(){jQuery('.show-hover').hide();jQuery('.show-first').fadeIn(10);});});function changeBgColor(rd_id,element){if(element=="footer"){jQuery('.b_head').css('background-color','#'+jQuery('#'+rd_id).val());jQuery('.b_body_f').css('background-color','#'+jQuery('#'+rd_id).val());jQuery('#link-color').val('#'+jQuery('#'+rd_id).val());jQuery.cookie(cookies_prefix+"_b_f_color",'#'+ jQuery('#'+rd_id).val(),{expires:365,path:'/'});}
else if(element=="content"){jQuery('#main').css('background-color','#'+jQuery('#'+rd_id).val());jQuery('#content-link-color').val('#'+jQuery('#'+rd_id).val());jQuery.cookie(cookies_prefix+"_content_bg_color",'#'+ jQuery('#'+rd_id).val(),{expires:365,path:'/'});}
return false;}
function setPickedColor(a,element){if(element=='footer'){jQuery('.b_f_c').css('background-color',a);jQuery.cookie(cookies_prefix+"_footer_bg_color",a,{expires:365,path:'/'});}
else if(element=="content"){jQuery('body').css('background-color',a);jQuery.cookie(cookies_prefix+"_content_bg_color",a,{expires:365,path:'/'});}}
function setBgColor(rb_id,element){jQuery('#'+ rb_id).trigger('click');changeBgColor(rb_id,element);}
function setBgImage(rb_id){jQuery('#'+ rb_id).trigger('click');changeBgImage(rb_id);}
jQuery(function(){jQuery('.keyboard-demo').click(function(){jQuery('#big-keyboard').slideToggle();var top=jQuery('body').offset().top;jQuery.scrollTo(top,400);});});jQuery(function(){jQuery('.close').click(function(){jQuery(this).parent().parent().slideToggle();});});function viewPort(){wSizes=[1200,960,768,480,320,240];wSizesClasses=['w1200','w960','w768','w480','w320','w240'];var size=jQuery(this).width();for(var i=0;i<wSizes.length;i++){if(size>=wSizes[i]){jQuery('.fb_iframe_widget iframe,.fb_iframe_widget span').css({'width':jQuery('#primary').width()});break;}}
if(typeof(FB)!='undefined'){FB.Event.subscribe('xfbml.render',function(response){FB.Canvas.setAutoGrow();});}}